# Generated by Django 3.0.3 on 2020-05-01 18:08
import pandas as pd

from django.db import migrations


def forward(apps, schema_editor):
    Question = apps.get_model('questions.Question')
    Label = apps.get_model('questions.Label')

    df = pd.read_csv('model/data/dataset.csv')
    for index, row in df.iterrows():
        question, _ = Question.objects.get_or_create(text=row['Question'])
        label, _ = Label.objects.get_or_create(identifier=row['Class'])
        question.label = label
        question.save()


def backward(apps, schema_editor):
    Question = apps.get_model('questions.Question')
    Label = apps.get_model('questions.Label')

    Question.objects.all().delete()
    Label.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
