# Generated by Django 3.0.3 on 2020-05-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200501_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='identifier',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
