# Generated by Django 3.0.3 on 2020-05-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200501_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='identifier',
            new_name='slug',
        ),
    ]
